# LSTM Coffee Price

# 1. Ambient preparation

In [4]:
from IPython.display import display, HTML

display(HTML("<style>.container {widht: 100% !important;}</style>"))

## 1.1. Import packages

In [5]:
import subprocess
import sys
import os
import yfinance
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import yfinance as yf

import pygame

import torch

## 1.2. GPU check

In [6]:
if torch.cuda.is_available():
    print("__CUDNN VERSION:", torch.backends.cudnn.version())
    print("Device Name:", torch.cuda.get_device_name(0))
    device = 'cuda'
else:
    print("CUDA is not available.")
    device = 'cpu'

print('Device:', device)

__CUDNN VERSION: 91900
Device Name: NVIDIA GeForce GTX 1050 Ti
Device: cuda

# 2. Dataset

In [7]:
coffee = yf.download("KC=F", start="2006-04-01", end="2026-04-01", interval="1d")
dollar = yf.download("BRL=X", start="2006-04-01", end="2026-04-01", interval="1d")

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

In [8]:
coffee.head()

Price            Close        High         Low        Open Volume
Ticker            KC=F        KC=F        KC=F        KC=F   KC=F
Date
2006-04-03  109.449997  110.699997  106.500000  106.500000  12568
2006-04-04  107.050003  110.699997  106.900002  109.800003  10654
2006-04-05  108.050003  110.699997  106.800003  107.699997  11354
2006-04-06  108.849998  110.650002  107.699997  110.000000   8680
2006-04-07  108.349998  109.699997  108.000000  109.300003  19917

In [9]:
dollar.head()

Price        Close    High     Low    Open Volume
Ticker       BRL=X   BRL=X   BRL=X   BRL=X  BRL=X
Date
2006-04-03  2.1479  2.1657  2.1479  2.1618      0
2006-04-04  2.1255  2.1379  2.1368  2.1370      0
2006-04-05  2.1336  2.1336  2.1237  2.1288      0
2006-04-06  2.1292  2.1360  2.1228  2.1298      0
2006-04-07  2.1352  2.1352  2.1257  2.1263      0

In [10]:
coffee = coffee[['Close']]
dollar = dollar[['Close']]

dollar

Price        Close
Ticker       BRL=X
Date
2006-04-03  2.1479
2006-04-04  2.1255
2006-04-05  2.1336
2006-04-06  2.1292
2006-04-07  2.1352
...            ...
2026-03-25  5.2326
2026-03-26  5.2368
2026-03-27  5.2351
2026-03-30  5.2380
2026-03-31  5.2640

[5175 rows x 1 columns]

In [11]:
df = coffee.join(dollar, how='inner', lsuffix='_coffee', rsuffix='_dolar')
df = df.dropna()

df

Price            Close
Ticker            KC=F   BRL=X
Date
2006-04-03  109.449997  2.1479
2006-04-04  107.050003  2.1255
2006-04-05  108.050003  2.1336
2006-04-06  108.849998  2.1292
2006-04-07  108.349998  2.1352
...                ...     ...
2026-03-25  316.100006  5.2326
2026-03-26  307.649994  5.2368
2026-03-27  301.700012  5.2351
2026-03-30  292.549988  5.2380
2026-03-31  298.350006  5.2640

[4991 rows x 2 columns]